create table if not exists public.orders (
  id bigint generated always as identity primary key,
  product_id text,
  product_name text,
  unit_price integer,
  customer_name text not null,
  contact_info text not null,
  quantity integer not null,
  delivery_option text not null,
  delivery_fee integer not null default 0,
  total_amount integer not null,
  address text,
  notes text,
  image_name text,
  image_data_url text,
  image_storage_path text,
  image_public_url text,
  payment_status text not null default 'pending',
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  confirmation_email_sent_at timestamptz,
  created_at timestamptz not null default now()
);
